version: '3'
services:
  scoutspyder:
    restart: always
    container_name: 'crawler-api'
    build: .
    ports:
      - '8000:8000'
  selenium:
    restart: always
    container_name: 'crawler-selenium'
    image: 'selenium/standalone-chrome'
    volumes:
      - /dev/shm:/dev/shm
  redis:
    restart: always
    container_name: 'crawler-redis'
    image: 'redis'