version: '3'
services:
  scoutspyder:
    restart: always
    container_name: 'crawler-api'
    build:
      context: ../
      dockerfile: ./Docker/Dockerfile
    ports:
      - '8000:8000'
  selenium:
    restart: always
    container_name: 'crawler-selenium'
    image: 'selenium/standalone-chrome'
    volumes:
      - /dev/shm:/dev/shm
networks:
  default:
    external:
      name: scoutspyder