FROM python:slim
RUN apt update && apt upgrade -y
RUN useradd -M scoutspyder
COPY --chown=scoutspyder:scoutspyder . /opt/scoutspyder
WORKDIR /opt/scoutspyder
RUN pip install -r requirements.txt
RUN rm -rf .git .gitignore Docker requirements.txt
USER scoutspyder
WORKDIR /opt/scoutspyder/Backend
EXPOSE 8000
CMD ["uvicorn", "--app-dir", "../Api", "--workers", "2", "--host", "0.0.0.0", "--port", "8000", "--forwarded-allow-ips", "172.16.0.1", "ScoutSpyder:app"]