version: '3'
services:
  scoutspyder-crawler:
    restart: unless-stopped
    container_name: 'crawler'
    build:
      context: ../
  selenium:
    restart: unless-stopped
    container_name: 'crawler-selenium'
    image: 'selenium/standalone-chrome'
    volumes:
      - /dev/shm:/dev/shm
networks:
  default:
    external:
      name: scoutspyder