FROM python
RUN apt update && apt upgrade -y
RUN useradd -M scoutspyder
COPY --chown=scoutspyder:scoutspyder . /opt/scoutspyder
WORKDIR /opt/scoutspyder
RUN pip install -r requirements.txt
RUN rm -rf .git .gitignore Docker requirements.txt
USER scoutspyder
WORKDIR /opt/scoutspyder/Backend
CMD ["python", "main_rabbitmq.py"]