version: '3'
services:
  scoutspyder-crawler:
    restart: unless-stopped
    container_name: 'crawler'
    build:
      context: ../
    environment:
      - DB_USERNAME=scoutspyder
      - DB_PASSWORD=XXXXXXXXXX
      - RQ_USERNAME=scoutspyder
      - RQ_PASSWORD=XXXXXXXXXX
    depends_on:
      - selenium
  selenium:
    restart: unless-stopped
    container_name: 'crawler-selenium'
    image: 'selenium/standalone-chrome'
    volumes:
      - /dev/shm:/dev/shm
networks:
  default:
    external:
      name: scoutspyder